package edu.bu.met.cs633

import javax.annotation.Generated

@Generated(value = ["JHipster"], comments = "Generated by JHipster 7.9.3")
@Retention(AnnotationRetention.SOURCE)
@Target
annotation class GeneratedByJHipster
